### PR TITLE
multi-language reply support 

### PR DESCRIPTION
**Pull request by MiuKaShi**
Hi, I have try to add this function, If you think it's suitable, you can accept

### CODE REVIEW

**Comment by james1236** [comment]
Hi, thanks for the pull request, but the prompt doesn't work since it also translates the `line=` at the start of each message which is what the plugin uses to get the line number for each suggestion

**Comment by MiuKaShi** [comment]
Thank you for pointing out the problem, I have fixed it based on your reply

**Comment by james1236** [comment]
When using the additional instruction `"Respond only in french, but keep the text 'line=' and the line number in english"` it still doesn't reliably keep the text `line=` the same, or reliably translate the suggestions with `gpt-3.5-turbo`, although it works perfectly in my testing with French or Chinese using `gpt-4`. With Arabic, it still translates line numbers sometimes which causes it to lose suggestions but it works well enough

It would be great to have this feature. I think it would require a longer prompt an example/training data to get it working with `gpt-3.5-turbo`, otherwise it could be made clear that it is experimental and only works with `gpt-4`

**Comment by james1236** [comment]
When using the additional instruction `"Respond only in french, but keep the text 'line=' and the line number in english"` it still doesn't reliably keep the text `line=` the same, or reliably translate the suggestions with `gpt-3.5-turbo`, although it works perfectly in my testing with French or Chinese using `gpt-4`. With Arabic, it still translates line numbers sometimes which causes it to lose suggestions but it works well enough

It would be great to have this feature. I think it would require a longer prompt an example/training data to get it working with `gpt-3.5-turbo`, otherwise it could be made clear that it is experimental and only works with `gpt-4`

For implementation, it could be a key called `language_experimental` which is unset by default, and commented out with a value like `japanese` in the example config (and a note saying "Only works in gpt-4"). When the value is `nil` or `english` (case-insensitive), nothing would happen. When the value is something else, the string `"Respond only in " .. language .. ", but keep the text 'line=' and the line number in english"` would be appended to whatever the current `additional_instruction` is

Thank you for suggesting #13 and working on this feature! I am happy to implement this, unless you're up for the task! 😄

**Comment by MiuKaShi** [comment]
Thanks for your reply, here I propose another approach to solve this problem. I see that when defining the system role in fewshot.lua, the response format `line=<num>: <issue and proposed solution>` is specified. So, my approach is to send a instruction

`"Respond the <issue and proposed solution> part in french, but keep the line=<num>: part in english"`

Currently, under `gpt-3.5-turbo` I tested this method for Chinese, Japanese, French and Arabic. They all work very well.

If you have time, please test. Any feedback would be greatly appreciate.

**Comment by james1236** [comment]
My problem was the text `<system>When responding with line=, ` and `</system>` surrounding additional instructions which was making results worse on `gpt-3.5-turbo`, so I've removed the those (fca2613b152be4e3e582f16920e596b3b2654763), putting additional instructions just on a new line like you're doing. Now it works very well, thank you!

The text `"Respond with the <issue and proposed solution> part in arabic, but keep the line=<num>: part in english"` does work well, but the new text `"Respond only in arabic, but keep the 'line=<num>:' part in english"` responds in the target language every time! I don't think this needs to be called `language_experimental` now, just `language` is fine

Would you like to update your pull request or should I start implementing this?

(Also, languages such as `pirate` and `LOLCAT` seem to work well too 😂)

**Comment by MiuKaShi** [comment]
Thanks for your feedback, I've updated my pull based on your suggestion and the language function should work fine now.  Hope openai open GPT4 API again, so we don't have to face such problems.😅

**Comment by james1236** [comment]
Thank you very much 😄

**Pull request merged**
